// Chess opening database — SAN move sequences mapped to opening names.
// getOpeningName returns the most specific (longest) matching opening.

export interface Opening {
  moves: string[];
  name: string;
}

export const OPENINGS: Opening[] = [
  // ── 1. e4 e5 ────────────────────────────────────────────────────────────────
  { moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","Re1","b5","Bb3","d6","c3","O-O","h3","Na5","Bc2","c5","d4"], name: "Ruy Lopez, Closed" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Nxe4","d4","b5","Bb3","d5","dxe5","Be6"], name: "Ruy Lopez, Open" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","Re1","b5","Bb3","O-O","d4"], name: "Ruy Lopez, Closed" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O"], name: "Ruy Lopez, Closed" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","Nf6","O-O","Nxe4","d4","Nd6","Bxc6","dxc6","dxe5","Nf5"], name: "Berlin Endgame" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","Nf6"], name: "Ruy Lopez, Berlin Defense" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4"], name: "Ruy Lopez, Morphy Defense" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","Bc5"], name: "Ruy Lopez, Classical" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5","d6"], name: "Ruy Lopez, Steinitz Defense" },
  { moves: ["e4","e5","Nf3","Nc6","Bb5"], name: "Ruy Lopez" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O"], name: "Evans Gambit, Main Line" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4"], name: "Evans Gambit" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+"], name: "Giuoco Piano, Moeller Attack" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4"], name: "Giuoco Piano, Modern" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5"], name: "Italian, Giuoco Piano" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","d5","exd5","Na5","Bb5+","c6","dxc6","bxc6","Be2","h6","Nf3","e4"], name: "Fried Liver Attack Declined" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","d5","exd5","Nxd5","Nxf7"], name: "Fried Liver Attack" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5"], name: "Italian, Fried Liver Attack" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6"], name: "Italian, Two Knights Defense" },
  { moves: ["e4","e5","Nf3","Nc6","Bc4"], name: "Italian Game" },
  { moves: ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Bc5","Be3","Qf6","c3","Nge7"], name: "Scotch, Göring Gambit-ish" },
  { moves: ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Nf6","Nxc6","bxc6","e5","Qe7","Qe2","Nd5","c4","Ba6"], name: "Scotch, Mieses Variation" },
  { moves: ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Bc5"], name: "Scotch, Classical" },
  { moves: ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4"], name: "Scotch Game" },
  { moves: ["e4","e5","Nf3","Nc6","d4","exd4","Bc4"], name: "Scotch Gambit" },
  { moves: ["e4","e5","Nf3","Nc6","d4","exd4","c3"], name: "Göring Gambit" },
  { moves: ["e4","e5","Nf3","Nc6","d4"], name: "Scotch Game" },
  { moves: ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Nc6","O-O","Be7"], name: "Petrov, Classical" },
  { moves: ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4"], name: "Petrov's Defense, Classical" },
  { moves: ["e4","e5","Nf3","Nf6"], name: "Petrov's Defense" },
  { moves: ["e4","e5","Nf3","d6","d4","Nd7","Bc4","c6","O-O","Be7"], name: "Philidor, Hanham Variation" },
  { moves: ["e4","e5","Nf3","d6"], name: "Philidor Defense" },
  { moves: ["e4","e5","Nf3","f5"], name: "Latvian Gambit" },
  { moves: ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Nf3","Be7"], name: "Vienna, Falkbeer" },
  { moves: ["e4","e5","Nc3","Bc5","f4","d6","Nf3","Nc6","Bc4"], name: "Vienna, Paulsen" },
  { moves: ["e4","e5","Nc3","Nc6","f4"], name: "Vienna Gambit" },
  { moves: ["e4","e5","Nc3","Nc6"], name: "Vienna Game" },
  { moves: ["e4","e5","Nc3","Nf6"], name: "Vienna Game" },
  { moves: ["e4","e5","f4","exf4","Nf3","g5","h4","g4","Ne5","Nf6","Bc4","d5","exd5","Bd6"], name: "King's Gambit, Kieseritzky" },
  { moves: ["e4","e5","f4","exf4","Nf3","g5","Bc4","g4","O-O"], name: "King's Gambit, Muzio" },
  { moves: ["e4","e5","f4","exf4","Nf3","g5","Bc4"], name: "King's Gambit, Bishop's Gambit" },
  { moves: ["e4","e5","f4","exf4","Nf3","d6"], name: "King's Gambit Accepted, Fischer Defense" },
  { moves: ["e4","e5","f4","exf4","Nf3"], name: "King's Gambit Accepted" },
  { moves: ["e4","e5","f4","exf4","Bc4"], name: "King's Gambit, Bishop's Gambit" },
  { moves: ["e4","e5","f4","exf4"], name: "King's Gambit Accepted" },
  { moves: ["e4","e5","f4","d5","exd5","exf4"], name: "King's Gambit Declined, Falkbeer" },
  { moves: ["e4","e5","f4","d5"], name: "King's Gambit, Falkbeer Counter" },
  { moves: ["e4","e5","f4","Bc5"], name: "King's Gambit Declined, Classical" },
  { moves: ["e4","e5","f4"], name: "King's Gambit" },
  { moves: ["e4","e5","d4","exd4","c3","dxc3","Bc4","cxb2","Bxb2"], name: "Danish Gambit Accepted" },
  { moves: ["e4","e5","d4","exd4","c3"], name: "Danish Gambit" },
  { moves: ["e4","e5","d4","exd4"], name: "Center Game" },
  { moves: ["e4","e5","Nf3","Nc6"], name: "King's Knight Opening" },
  { moves: ["e4","e5","Nf3"], name: "King's Pawn, King's Knight" },
  { moves: ["e4","e5"], name: "Open Game" },

  // ── Sicilian Defense ────────────────────────────────────────────────────────
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Bg5","e6","f4","Qb6"], name: "Sicilian, Najdorf Poisoned Pawn" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Bg5","e6","f4"], name: "Sicilian, Najdorf English Attack" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","Ng4","Bc1","Nf6"], name: "Sicilian, Najdorf English Attack" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3"], name: "Sicilian, Najdorf English Attack" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Bc4"], name: "Sicilian, Najdorf Fischer-Sozin" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","f3"], name: "Sicilian, Najdorf English Attack" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6"], name: "Sicilian, Najdorf Variation" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","d5"], name: "Sicilian Dragon, Yugoslav Attack" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3"], name: "Sicilian, Dragon Yugoslav" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Bc4"], name: "Sicilian, Dragon Fischer-Sozin" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6"], name: "Sicilian, Dragon Variation" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6","Be2","a6","O-O","Qc7","f4"], name: "Sicilian, Scheveningen Keres" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6"], name: "Sicilian, Scheveningen" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e5","Nb3","Be7"], name: "Sicilian, Boleslavsky" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e5"], name: "Sicilian, Boleslavsky" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3"], name: "Sicilian, Open" },
  { moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","d6","Bg5"], name: "Sicilian, Richter-Rauzer" },
  { moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","e5"], name: "Sicilian, Classical Boleslavsky" },
  { moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","d6"], name: "Sicilian, Classical" },
  { moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7"], name: "Sicilian, Accelerated Dragon" },
  { moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6"], name: "Sicilian, Accelerated Dragon" },
  { moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4"], name: "Sicilian, Classical" },
  { moves: ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","Nf6","Nc3","Bb4"], name: "Sicilian, Kan Variation" },
  { moves: ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","Nc6"], name: "Sicilian, Taimanov" },
  { moves: ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","a6"], name: "Sicilian, Kan" },
  { moves: ["e4","c5","Nf3","e6","d4","cxd4","Nxd4"], name: "Sicilian, Paulsen" },
  { moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4"], name: "Sicilian, Open" },
  { moves: ["e4","c5","Nf3","d6","d4"], name: "Sicilian, Open" },
  { moves: ["e4","c5","Nf3","Nc6","d4"], name: "Sicilian, Open" },
  { moves: ["e4","c5","Nc3","Nc6","g3","g6","Bg2","Bg7","d3"], name: "Sicilian, Closed" },
  { moves: ["e4","c5","Nc3","Nc6","g3"], name: "Sicilian, Closed" },
  { moves: ["e4","c5","Nc3"], name: "Sicilian, Closed" },
  { moves: ["e4","c5","c3","Nf6","e5","Nd5","d4","cxd4","Nf3"], name: "Sicilian, Alapin, Anti-Sveshnikov" },
  { moves: ["e4","c5","c3","d5","exd5","Qxd5","d4"], name: "Sicilian, Alapin" },
  { moves: ["e4","c5","c3"], name: "Sicilian, Alapin" },
  { moves: ["e4","c5","d4","cxd4","c3","dxc3","Nxc3"], name: "Sicilian, Smith-Morra Gambit" },
  { moves: ["e4","c5","Nf3","Nc6"], name: "Sicilian Defense" },
  { moves: ["e4","c5","Nf3","d6"], name: "Sicilian Defense" },
  { moves: ["e4","c5","Nf3","e6"], name: "Sicilian Defense" },
  { moves: ["e4","c5","Nf3"], name: "Sicilian Defense, Open" },
  { moves: ["e4","c5"], name: "Sicilian Defense" },

  // ── French Defense ──────────────────────────────────────────────────────────
  { moves: ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7"], name: "French, Winawer, Poison Pawn" },
  { moves: ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3"], name: "French, Winawer, Poison Pawn" },
  { moves: ["e4","e6","d4","d5","Nc3","Bb4","e5"], name: "French, Winawer, Advance" },
  { moves: ["e4","e6","d4","d5","Nc3","Bb4"], name: "French, Winawer Variation" },
  { moves: ["e4","e6","d4","d5","Nc3","Nf6","Bg5","dxe4","Nxe4","Nbd7"], name: "French, McCutcheon" },
  { moves: ["e4","e6","d4","d5","Nc3","Nf6","Bg5","Be7","e5","Nfd7","Bxe7","Qxe7"], name: "French, Classical, Steinitz" },
  { moves: ["e4","e6","d4","d5","Nc3","Nf6","Bg5"], name: "French, Classical, Chatard-Alekhine" },
  { moves: ["e4","e6","d4","d5","Nc3","Nf6","e5","Nfd7","f4"], name: "French, Classical, Steinitz" },
  { moves: ["e4","e6","d4","d5","Nc3","Nf6"], name: "French, Classical" },
  { moves: ["e4","e6","d4","d5","Nc3"], name: "French, Classical" },
  { moves: ["e4","e6","d4","d5","Nd2","Nf6","e5","Nfd7","Bd3","c5","c3"], name: "French, Tarrasch, Closed" },
  { moves: ["e4","e6","d4","d5","Nd2","c5","exd5","exd5","Ngf3","Nc6","Bb5"], name: "French, Tarrasch, Open" },
  { moves: ["e4","e6","d4","d5","Nd2","Nf6"], name: "French, Tarrasch" },
  { moves: ["e4","e6","d4","d5","Nd2"], name: "French, Tarrasch" },
  { moves: ["e4","e6","d4","d5","e5","c5","c3","Nc6","Nf3","Qb6"], name: "French, Advance, Milner-Barry" },
  { moves: ["e4","e6","d4","d5","e5","c5","c3"], name: "French, Advance" },
  { moves: ["e4","e6","d4","d5","e5"], name: "French, Advance Variation" },
  { moves: ["e4","e6","d4","d5","exd5","exd5"], name: "French, Exchange" },
  { moves: ["e4","e6","d4","d5","exd5"], name: "French, Exchange Variation" },
  { moves: ["e4","e6","d4","d5"], name: "French Defense" },
  { moves: ["e4","e6"], name: "French Defense" },

  // ── Caro-Kann ───────────────────────────────────────────────────────────────
  { moves: ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","h4","h6","Nf3","Nd7","h5","Bh7","Bd3","Bxd3","Qxd3","e6","Bf4","Ngf6","O-O-O"], name: "Caro-Kann, Classical, Main Line" },
  { moves: ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","h4"], name: "Caro-Kann, Classical" },
  { moves: ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5"], name: "Caro-Kann, Classical" },
  { moves: ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Nf3","Ngf6","Nxf6+","Nxf6","Ne5"], name: "Caro-Kann, Smyslov" },
  { moves: ["e4","c6","d4","d5","Nc3","dxe4","Nxe4"], name: "Caro-Kann, Classical" },
  { moves: ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","Ne7","O-O","c5"], name: "Caro-Kann, Advance, Short Variation" },
  { moves: ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2"], name: "Caro-Kann, Advance" },
  { moves: ["e4","c6","d4","d5","e5","Bf5"], name: "Caro-Kann, Advance" },
  { moves: ["e4","c6","d4","d5","e5"], name: "Caro-Kann, Advance" },
  { moves: ["e4","c6","d4","d5","Nd2","dxe4","Nxe4","Nf6","Nxf6+","exf6"], name: "Caro-Kann, Karpov" },
  { moves: ["e4","c6","d4","d5","Nd2"], name: "Caro-Kann, Tartakower" },
  { moves: ["e4","c6","d4","d5","Nc3"], name: "Caro-Kann, Classical" },
  { moves: ["e4","c6","d4","d5"], name: "Caro-Kann Defense" },
  { moves: ["e4","c6"], name: "Caro-Kann Defense" },

  // ── Other 1.e4 ──────────────────────────────────────────────────────────────
  { moves: ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bf5","Bc4","e6"], name: "Scandinavian, Main Line" },
  { moves: ["e4","d5","exd5","Qxd5","Nc3","Qd6","d4","Nf6","Nf3","g6"], name: "Scandinavian, Gubinsky-Melts" },
  { moves: ["e4","d5","exd5","Qxd5","Nc3","Qa5"], name: "Scandinavian, Main Line" },
  { moves: ["e4","d5","exd5","Qxd5","Nc3"], name: "Scandinavian Defense" },
  { moves: ["e4","d5","exd5","Nf6"], name: "Scandinavian, Icelandic Gambit" },
  { moves: ["e4","d5","exd5","c6"], name: "Scandinavian, Portuguese Variation" },
  { moves: ["e4","d5","exd5"], name: "Scandinavian Defense" },
  { moves: ["e4","d5"], name: "Scandinavian Defense" },
  { moves: ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","exd6","exd6","Nc3"], name: "Alekhine, Exchange" },
  { moves: ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","exd6"], name: "Alekhine, Exchange Variation" },
  { moves: ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","f4"], name: "Alekhine, Four Pawns Attack" },
  { moves: ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6"], name: "Alekhine's Defense, Modern" },
  { moves: ["e4","Nf6","e5","Nd5","d4","d6"], name: "Alekhine's Defense" },
  { moves: ["e4","Nf6","e5","Nd5","c4","Nb6","d4","d6"], name: "Alekhine, Modern" },
  { moves: ["e4","Nf6","e5","Nd5"], name: "Alekhine's Defense" },
  { moves: ["e4","Nf6"], name: "Alekhine's Defense" },
  { moves: ["e4","d6","d4","Nf6","Nc3","g6","f4","Bg7","Nf3","O-O","Be2"], name: "Pirc, Austrian Attack" },
  { moves: ["e4","d6","d4","Nf6","Nc3","g6","f4"], name: "Pirc, Austrian Attack" },
  { moves: ["e4","d6","d4","Nf6","Nc3","g6"], name: "Pirc Defense" },
  { moves: ["e4","d6","d4","Nf6","Nc3"], name: "Pirc Defense" },
  { moves: ["e4","d6","d4","Nf6"], name: "Pirc Defense" },
  { moves: ["e4","d6"], name: "Pirc Defense" },
  { moves: ["e4","g6","d4","Bg7","Nc3","d6","f4"], name: "Modern Defense, Austrian" },
  { moves: ["e4","g6","d4","Bg7","Nc3","d6"], name: "Modern Defense" },
  { moves: ["e4","g6","d4","Bg7"], name: "Modern Defense" },
  { moves: ["e4","g6"], name: "Modern Defense" },
  { moves: ["e4","b6","d4","Bb7","Bd3","Nf6","Nd2"], name: "Owen's Defense" },
  { moves: ["e4","b6"], name: "Owen's Defense" },
  { moves: ["e4","Nc6","Nf3","e5","Bc4"], name: "Nimzowitsch Defense" },
  { moves: ["e4","Nc6"], name: "Nimzowitsch Defense" },
  { moves: ["e4","a6"], name: "St. George Defense" },
  { moves: ["e4","b5"], name: "Polish Defense (as Black)" },
  { moves: ["e4"], name: "King's Pawn Opening" },

  // ── 1. d4 d5 ────────────────────────────────────────────────────────────────
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","cxd5","exd5","Bg5","c6","e3","Bf5"], name: "QGD, Exchange Variation" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5","Be7","e3","O-O","Nf3","h6","Bh4","b6"], name: "QGD, Orthodox, Tartakower" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5","Be7","e3","O-O","Nf3","Nbd7"], name: "QGD, Orthodox Defense" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5","Be7","e3"], name: "QGD, Classical Variation" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5"], name: "QGD, Orthodox Defense" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","Nf3","Be7","Bf4"], name: "QGD, Carlsbad" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6","Nf3"], name: "QGD, Three Knights" },
  { moves: ["d4","d5","c4","e6","Nc3","Nf6"], name: "Queen's Gambit Declined" },
  { moves: ["d4","d5","c4","e6","Nc3"], name: "Queen's Gambit Declined" },
  { moves: ["d4","d5","c4","e6","Nf3","Nf6","Nc3"], name: "QGD, Three Knights" },
  { moves: ["d4","d5","c4","e6","Nf3","Nf6"], name: "Queen's Gambit Declined" },
  { moves: ["d4","d5","c4","e6"], name: "Queen's Gambit Declined" },
  { moves: ["d4","d5","c4","dxc4","Nf3","Nf6","e3","e6","Bxc4","c5","O-O","a6"], name: "QGA, Classical" },
  { moves: ["d4","d5","c4","dxc4","Nf3","Nf6","e3","e6","Bxc4"], name: "QGA, Classical" },
  { moves: ["d4","d5","c4","dxc4","e4","Nf6","e5","Nd5","Bxc4"], name: "QGA, Central Variation" },
  { moves: ["d4","d5","c4","dxc4","e3","Nf6","Nf3","e6","Bxc4"], name: "QGA, Classical" },
  { moves: ["d4","d5","c4","dxc4","Nf3"], name: "Queen's Gambit Accepted" },
  { moves: ["d4","d5","c4","dxc4","e3"], name: "Queen's Gambit Accepted" },
  { moves: ["d4","d5","c4","dxc4"], name: "Queen's Gambit Accepted" },
  { moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","dxc4","a4","Bf5","e3"], name: "Slav, Czech Variation" },
  { moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","dxc4","a4"], name: "Slav, Czech" },
  { moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","e6","e3","Nbd7","Bd3","dxc4","Bxc4","b5"], name: "Slav, Meran Variation" },
  { moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","e6","e3"], name: "Slav, Semi-Meran" },
  { moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3"], name: "Slav Defense, Main Line" },
  { moves: ["d4","d5","c4","c6","Nf3","Nf6"], name: "Slav Defense" },
  { moves: ["d4","d5","c4","c6","Nf3"], name: "Slav Defense" },
  { moves: ["d4","d5","c4","c6","Nc3","Nf6","e3","e6","Nf3","Nbd7","Bd3","dxc4","Bxc4","b5"], name: "Semi-Slav, Meran" },
  { moves: ["d4","d5","c4","c6","Nc3","Nf6","e3","e6"], name: "Semi-Slav Defense" },
  { moves: ["d4","d5","c4","c6","Nc3","Nf6","e3"], name: "Semi-Slav" },
  { moves: ["d4","d5","c4","c6","Nc3"], name: "Slav Defense" },
  { moves: ["d4","d5","c4","c6"], name: "Slav Defense" },
  { moves: ["d4","d5","c4","Nf6","Nc3","e6","Nf3","c5","cxd5","Nxd5","e4"], name: "QGD, Tarrasch-like" },
  { moves: ["d4","d5","c4","Nc6","Nf3","Bg4","e3","e6","cxd5","exd5"], name: "Chigorin Defense" },
  { moves: ["d4","d5","c4","Nc6"], name: "Chigorin Defense" },
  { moves: ["d4","d5","c4"], name: "Queen's Gambit" },
  { moves: ["d4","d5","Nf3","Nf6","Bf4","e6","e3","Bd6","Bg3","O-O","Nbd2","c5"], name: "London System" },
  { moves: ["d4","d5","Nf3","Nf6","Bf4","e6","e3"], name: "London System" },
  { moves: ["d4","d5","Nf3","Nf6","Bf4"], name: "London System" },
  { moves: ["d4","d5","Nf3","Nf6","c4","e6","Nc3","Bb4"], name: "Nimzo-Indian Transposition" },
  { moves: ["d4","d5","Nf3","Nf6","e3","e6","Bd3","c5","c3"], name: "Colle System" },
  { moves: ["d4","d5","Nf3","Nf6","e3"], name: "Colle System" },
  { moves: ["d4","d5","Nf3"], name: "Queen's Pawn" },
  { moves: ["d4","d5"], name: "Queen's Pawn Opening" },

  // ── 1. d4 Nf6 ───────────────────────────────────────────────────────────────
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Nd2","a5","a3"], name: "King's Indian, Petrosian" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","d5","Nh5","Nh2","Qe8"], name: "King's Indian, Mar del Plata" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Nd2"], name: "King's Indian, Classical" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5"], name: "King's Indian, Classical" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O"], name: "King's Indian, Classical" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","dxc5","dxc5","Qxd8"], name: "King's Indian, Sämisch" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3"], name: "King's Indian, Sämisch Attack" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Be2","O-O","Bg5","h6","Be3","Nc6"], name: "King's Indian, Averbakh" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Be2","O-O","Bg5"], name: "King's Indian, Averbakh Variation" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2"], name: "King's Indian, Classical Main Line" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O"], name: "King's Indian Defense" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3"], name: "King's Indian Defense" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6"], name: "King's Indian Defense" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5","cxd5","Nxd5","e4","Nxc3","bxc3","Bg7","Nf3","c5","Rb1"], name: "Grünfeld, Russian System" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5","cxd5","Nxd5","e4","Nxc3","bxc3","Bg7","Bc4"], name: "Grünfeld, Classical" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5","cxd5","Nxd5","e4","Nxc3","bxc3","Bg7","Nf3"], name: "Grünfeld, Exchange" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5","cxd5","Nxd5","e4"], name: "Grünfeld, Exchange Variation" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5","cxd5","Nxd5"], name: "Grünfeld Defense, Exchange" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5","Nf3","Bg7","Bf4","O-O","e3","c5"], name: "Grünfeld, Anti-Grünfeld" },
  { moves: ["d4","Nf6","c4","g6","Nc3","d5"], name: "Grünfeld Defense" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7","Nf3"], name: "King's Indian, Three Pawns" },
  { moves: ["d4","Nf6","c4","g6","Nc3","Bg7"], name: "King's Indian / Grünfeld Setup" },
  { moves: ["d4","Nf6","c4","g6","Nc3"], name: "King's Indian Defense" },
  { moves: ["d4","Nf6","c4","g6","g3","Bg7","Bg2","d5","cxd5","Nxd5","Nf3"], name: "King's Indian, Fianchetto, Grünfeld" },
  { moves: ["d4","Nf6","c4","g6","g3","Bg7","Bg2","O-O","Nc3","d6","Nf3","Nbd7"], name: "King's Indian, Fianchetto" },
  { moves: ["d4","Nf6","c4","g6","g3"], name: "King's Indian, Fianchetto" },
  { moves: ["d4","Nf6","c4","g6"], name: "King's Indian Setup" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","e3","O-O","Bd3","d5","Nf3","c5","O-O","Nc6","a3","Bxc3","bxc3"], name: "Nimzo-Indian, Rubinstein" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","e3","O-O","Bd3","c5","Nf3","d5","O-O","dxc4","Bxc4","Nbd7"], name: "Nimzo-Indian, Normal Line" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","e3","O-O","Bd3","c5","Nf3"], name: "Nimzo-Indian, Rubinstein" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","e3","b6","Ne2","Ba6","Ng3"], name: "Nimzo-Indian, Zürich" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","Qc2","O-O","a3","Bxc3+","Qxc3"], name: "Nimzo-Indian, Classical" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","Qc2"], name: "Nimzo-Indian, Classical" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","f3"], name: "Nimzo-Indian, Sämisch" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","a3","Bxc3+","bxc3"], name: "Nimzo-Indian, Sämisch" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","a3"], name: "Nimzo-Indian, Sämisch" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4","e3"], name: "Nimzo-Indian, Rubinstein" },
  { moves: ["d4","Nf6","c4","e6","Nc3","Bb4"], name: "Nimzo-Indian Defense" },
  { moves: ["d4","Nf6","c4","e6","Nf3","b6","g3","Bb7","Bg2","Be7","O-O","O-O","Nc3","Ne4"], name: "Queen's Indian, Petrosian" },
  { moves: ["d4","Nf6","c4","e6","Nf3","b6","g3","Bb7","Bg2","Be7","O-O","O-O"], name: "Queen's Indian, Fianchetto" },
  { moves: ["d4","Nf6","c4","e6","Nf3","b6","g3","Bb7","Bg2"], name: "Queen's Indian, Fianchetto" },
  { moves: ["d4","Nf6","c4","e6","Nf3","b6","e3","Bb7","Bd3","d5","O-O","Bd6"], name: "Queen's Indian, Classical" },
  { moves: ["d4","Nf6","c4","e6","Nf3","b6","g3"], name: "Queen's Indian Defense, Fianchetto" },
  { moves: ["d4","Nf6","c4","e6","Nf3","b6"], name: "Queen's Indian Defense" },
  { moves: ["d4","Nf6","c4","e6","Nc3","d5","cxd5","exd5","Bg5"], name: "QGD, Exchange" },
  { moves: ["d4","Nf6","c4","e6","Nc3","d5","Bg5","Be7","e3","O-O","Nf3","Nbd7"], name: "QGD, Classical" },
  { moves: ["d4","Nf6","c4","e6","Nc3","d5"], name: "Queen's Gambit Declined, Indian" },
  { moves: ["d4","Nf6","c4","e6","Nc3"], name: "Queen's Gambit Declined" },
  { moves: ["d4","Nf6","c4","e6","Nf3","d5","Nc3","Be7","Bf4","O-O","e3","c6"], name: "QGD, Tartakower" },
  { moves: ["d4","Nf6","c4","e6","Nf3","d5","Nc3"], name: "Queen's Gambit Declined" },
  { moves: ["d4","Nf6","c4","e6","Nf3","d5"], name: "Queen's Gambit Declined" },
  { moves: ["d4","Nf6","c4","e6","Nf3"], name: "Queen's Indian / QGD" },
  { moves: ["d4","Nf6","c4","e6"], name: "Indian Defense, e6" },
  { moves: ["d4","Nf6","c4","c5","d5","e6","Nc3","exd5","cxd5","d6","e4","g6"], name: "Benoni, Modern" },
  { moves: ["d4","Nf6","c4","c5","d5","e6","Nc3","exd5","cxd5"], name: "Benoni Defense, Czech" },
  { moves: ["d4","Nf6","c4","c5","d5","e6","Nc3","exd5"], name: "Benoni Defense" },
  { moves: ["d4","Nf6","c4","c5","d5","e6"], name: "Benoni Defense" },
  { moves: ["d4","Nf6","c4","c5","d5","b5","cxb5","a6"], name: "Benko Gambit" },
  { moves: ["d4","Nf6","c4","c5","d5","b5","cxb5"], name: "Benko Gambit" },
  { moves: ["d4","Nf6","c4","c5","d5"], name: "Benoni Defense" },
  { moves: ["d4","Nf6","c4","c5"], name: "Benoni Defense" },
  { moves: ["d4","Nf6","c4","d5","cxd5","Nxd5","Nf3","g6","g3","Bg7","Bg2","Nb6"], name: "Neo-Grünfeld" },
  { moves: ["d4","Nf6","c4","d5","Nc3","Bf5"], name: "Queen's Gambit Declined, Chigorin-like" },
  { moves: ["d4","Nf6","c4","d5","Nf3","e6"], name: "Queen's Gambit Declined" },
  { moves: ["d4","Nf6","c4","d5"], name: "Queen's Gambit Declined" },
  { moves: ["d4","Nf6","c4"], name: "Indian Defense" },
  { moves: ["d4","Nf6","Nf3","g6","g3","Bg7","Bg2","O-O","O-O","d6","Nc3","Nbd7"], name: "King's Indian, Fianchetto" },
  { moves: ["d4","Nf6","Nf3","g6","g3","Bg7","Bg2","O-O","c4"], name: "King's Indian, Fianchetto" },
  { moves: ["d4","Nf6","Nf3","g6","g3"], name: "King's Indian Attack" },
  { moves: ["d4","Nf6","Nf3","e6","c4","b6"], name: "Queen's Indian" },
  { moves: ["d4","Nf6","Nf3","d5","c4"], name: "Queen's Gambit" },
  { moves: ["d4","Nf6","Nf3"], name: "Indian Defense" },
  { moves: ["d4","Nf6"], name: "Indian Defense" },

  // ── Other 1.d4 ──────────────────────────────────────────────────────────────
  { moves: ["d4","f5","c4","Nf6","Nc3","e6","Nf3","Bb4","e3","b6"], name: "Dutch, Nimzo-Dutch" },
  { moves: ["d4","f5","c4","Nf6","Nc3","e6","g3","d5","cxd5","exd5","Bg2"], name: "Dutch, Stonewall" },
  { moves: ["d4","f5","c4","Nf6","g3","e6","Bg2","d5","Nf3"], name: "Dutch, Leningrad" },
  { moves: ["d4","f5","c4","Nf6","Nc3","g6","g3","Bg7","Bg2","O-O"], name: "Dutch, Leningrad" },
  { moves: ["d4","f5","c4","Nf6","Nc3","g6"], name: "Dutch, Leningrad Variation" },
  { moves: ["d4","f5","c4"], name: "Dutch Defense" },
  { moves: ["d4","f5","Nf3","Nf6","g3","e6","Bg2","Be7","O-O","O-O","c4","d5"], name: "Dutch, Classical" },
  { moves: ["d4","f5","Nf3","e6","g3","Nf6","Bg2","d5","c4","c6"], name: "Dutch, Stonewall" },
  { moves: ["d4","f5"], name: "Dutch Defense" },
  { moves: ["d4","e5","dxe5","Nc6","Nf3","Qe7","Qd5","f6","Nc3"], name: "Englund Gambit, Charlick-Soller" },
  { moves: ["d4","e5","dxe5","Nc6"], name: "Englund Gambit" },
  { moves: ["d4","e5"], name: "Englund Gambit" },
  { moves: ["d4","c5","d5","e6","c4","exd5","cxd5","d6"], name: "Benoni, Czech" },
  { moves: ["d4","c5","d5","e6","Nc3"], name: "Benoni Defense" },
  { moves: ["d4","c5","d5"], name: "Benoni Defense" },
  { moves: ["d4","g6","c4","Bg7","Nc3","d6","e4","Nc6","Nge2","e5","d5"], name: "Modern Benoni / King's Indian" },
  { moves: ["d4","g6","c4","Bg7","Nc3","d6","e4"], name: "Modern Defense" },
  { moves: ["d4","g6"], name: "Modern Defense" },
  { moves: ["d4","b6","e4","Bb7","Bd3","f5","exf5","Bxg2"], name: "English Defense" },
  { moves: ["d4","b6"], name: "English Defense" },
  { moves: ["d4"], name: "Queen's Pawn Opening" },

  // ── 1. c4 — English Opening ─────────────────────────────────────────────────
  { moves: ["c4","e5","Nc3","Nf6","Nf3","Nc6","g3","d5","cxd5","Nxd5","Bg2"], name: "English, Reversed Dragon" },
  { moves: ["c4","e5","Nc3","Nf6","Nf3","Nc6","g3","Bb4","Bg2","O-O","O-O","e4","Ne1","Bxc3","bxc3"], name: "English, Four Knights" },
  { moves: ["c4","e5","Nc3","Nf6","Nf3","Nc6","g3","d5","cxd5"], name: "English, Reversed Dragon" },
  { moves: ["c4","e5","Nc3","Nf6","Nf3","Nc6"], name: "English, Four Knights" },
  { moves: ["c4","e5","Nc3","Nf6","g3","d5","cxd5","Nxd5","Bg2"], name: "English, Reversed Grünfeld" },
  { moves: ["c4","e5","Nc3","Nc6","g3","g6","Bg2","Bg7","d3","d6","e4"], name: "English, King's English" },
  { moves: ["c4","e5","Nc3","Nc6","g3","g6","Bg2"], name: "English, King's English" },
  { moves: ["c4","e5","Nc3","Nc6","Nf3","f5"], name: "English, Reversed Grand Prix" },
  { moves: ["c4","e5","Nc3","Nc6"], name: "English Opening, King's" },
  { moves: ["c4","e5","Nc3","Nf6"], name: "English Opening, Agincourt" },
  { moves: ["c4","e5","Nc3","d6"], name: "English Opening" },
  { moves: ["c4","e5","g3","Nf6","Bg2","d5","cxd5","Nxd5"], name: "English, Reversed Grünfeld" },
  { moves: ["c4","e5","Nc3"], name: "English Opening" },
  { moves: ["c4","e5","Nf3","Nc6","d4"], name: "English, Symmetrical" },
  { moves: ["c4","e5"], name: "English Opening, Symmetrical" },
  { moves: ["c4","Nf6","Nc3","g6","g3","Bg7","Bg2","O-O","d4","d6","Nf3","Nbd7"], name: "English, King's Indian" },
  { moves: ["c4","Nf6","Nc3","g6","g3","Bg7","Bg2","O-O","d4","d6"], name: "English, King's Indian" },
  { moves: ["c4","Nf6","Nc3","e6","e4","d5","cxd5","exd5","e5","Ne4","Nf3","Bg4"], name: "English, Agincourt" },
  { moves: ["c4","Nf6","Nc3","e6","Nf3","d5","d4"], name: "English → QGD" },
  { moves: ["c4","Nf6","Nc3","c5","g3","g6","Bg2","Bg7","Nf3","O-O","O-O","Nc6","d4","d5","cxd5","Nxd5"], name: "Symmetrical English" },
  { moves: ["c4","Nf6","Nc3","c5","g3","g6","Bg2","Bg7","Nf3","O-O","O-O","Nc6"], name: "Symmetrical English" },
  { moves: ["c4","Nf6","g3","g6","Bg2","Bg7","Nc3","O-O","e4","d6","Nge2"], name: "English, Botvinnik System" },
  { moves: ["c4","Nf6","g3","c6","Bg2","d5","cxd5","cxd5","d4"], name: "English, Caro-Kann" },
  { moves: ["c4","Nf6","Nf3","c5","Nc3","Nc6","g3","d5","cxd5","Nxd5","Bg2"], name: "English, Symmetrical" },
  { moves: ["c4","Nf6","Nf3","g6","g3","Bg7","Bg2","O-O","O-O","d6","Nc3","Nbd7"], name: "English, King's Indian" },
  { moves: ["c4","Nf6","Nf3","e6","Nc3","d5","d4"], name: "English → QGD" },
  { moves: ["c4","Nf6"], name: "English Opening" },
  { moves: ["c4","c5","Nf3","Nf6","Nc3","Nc6","g3","g6","Bg2","Bg7","O-O","O-O","d4","cxd4","Nxd4"], name: "Symmetrical English, Four Knights" },
  { moves: ["c4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","e6","g3","Qb6"], name: "Symmetrical, Hedgehog" },
  { moves: ["c4","c5","Nc3","Nf6","g3","d5","cxd5","Nxd5","Bg2"], name: "Symmetrical English" },
  { moves: ["c4","c5","Nf3","Nf6","Nc3","Nc6","g3","g6"], name: "English, Symmetrical" },
  { moves: ["c4","c5","Nc3","Nc6","g3","g6","Bg2"], name: "English, Symmetrical" },
  { moves: ["c4","c5"], name: "English, Symmetrical" },
  { moves: ["c4","d5","cxd5","c6"], name: "English, Caro-Kann" },
  { moves: ["c4","d5","cxd5","Nf6"], name: "English, Marshall" },
  { moves: ["c4","d5","cxd5","Qxd5","Nc3","Qa5","d4","Nf6"], name: "English Opening" },
  { moves: ["c4","d5","cxd5"], name: "English Opening" },
  { moves: ["c4","d5","Nc3","Nf6","d4"], name: "English → Queen's Gambit" },
  { moves: ["c4","d5","Nc3","d4","e3","Nc6","exd4","cxd4","d3"], name: "English, Reversed Sicilian" },
  { moves: ["c4","d5","Nc3"], name: "English Opening" },
  { moves: ["c4","e6","Nc3","d5","d4","Nf6"], name: "English → QGD" },
  { moves: ["c4","e6","d4","d5","Nc3"], name: "English → QGD" },
  { moves: ["c4","b6","Nc3","Bb7","d4","e6","e4","f5"], name: "English, Owen" },
  { moves: ["c4","g6","Nc3","Bg7","g3","Nf6","Bg2","O-O","d4","d6"], name: "English, King's Indian" },
  { moves: ["c4","Nc6","Nc3","e5","g3","g6","Bg2","Bg7","d3"], name: "English, Four Knights" },
  { moves: ["c4","Nc6","Nc3","Nf6","g3","g6","Bg2","d5","cxd5","Nxd5","Bxc6","bxc6","d3"], name: "English, Reversed Dragon" },
  { moves: ["c4","Nc6"], name: "English Opening" },
  { moves: ["c4","f5","Nc3","Nf6","d4","g6","g3","Bg7","Bg2","O-O","Nf3","d6"], name: "English, Dutch" },
  { moves: ["c4","f5"], name: "English, Dutch Variation" },
  { moves: ["c4"], name: "English Opening" },

  // ── 1. Nf3 — Réti & others ──────────────────────────────────────────────────
  { moves: ["Nf3","d5","c4","c6","Nc3","Nf6","d4","dxc4","a4","Bf5","e3","e6"], name: "Réti, Slav" },
  { moves: ["Nf3","d5","c4","c6","Nc3","Nf6","e3","Bf5","d4"], name: "Réti → Semi-Slav" },
  { moves: ["Nf3","d5","c4","e6","Nc3","Nf6","d4","Be7","Bf4","O-O","e3"], name: "Réti → QGD" },
  { moves: ["Nf3","d5","c4","dxc4","e3","Nf6","Bxc4","e6","O-O","c5","d4"], name: "Réti, QGA" },
  { moves: ["Nf3","d5","c4","d4","b4","Nf6","e3","dxe3","Bxe3","g6"], name: "Réti, Gambit" },
  { moves: ["Nf3","d5","c4","d4"], name: "Réti, Advance" },
  { moves: ["Nf3","d5","c4","Nf6","g3","e6","Bg2","Be7","O-O","O-O","d4","Nbd7"], name: "Réti Opening" },
  { moves: ["Nf3","d5","c4","c6","g3","Nf6","Bg2","Bf5","O-O","e6","d3","Nbd7"], name: "Réti → Slav" },
  { moves: ["Nf3","d5","c4","Nf6","g3"], name: "Réti Opening" },
  { moves: ["Nf3","d5","c4","e6","g3","Nf6","Bg2","Be7","O-O","O-O","d4","Nbd7","Qc2"], name: "Réti → QGD" },
  { moves: ["Nf3","d5","g3","c5","Bg2","Nc6","O-O","Nf6","d3","g6","Nbd2"], name: "King's Indian Attack" },
  { moves: ["Nf3","d5","g3","Nf6","Bg2","e6","O-O","Be7","d3","O-O"], name: "King's Indian Attack" },
  { moves: ["Nf3","d5","g3","g6","Bg2","Bg7","O-O","Nf6","d3","O-O","Nbd2"], name: "King's Indian Attack" },
  { moves: ["Nf3","d5","g3"], name: "King's Indian Attack" },
  { moves: ["Nf3","Nf6","c4","g6","Nc3","Bg7","e4","d6","d4"], name: "Réti → King's Indian" },
  { moves: ["Nf3","Nf6","c4","e6","Nc3","d5","d4"], name: "Réti → QGD" },
  { moves: ["Nf3","Nf6","c4","g6","g3","Bg7","Bg2","O-O","O-O","d6","Nc3","Nbd7"], name: "Réti, King's Indian" },
  { moves: ["Nf3","Nf6","c4","c5","g3","g6","Bg2","Bg7","O-O","O-O","Nc3","Nc6","d4"], name: "Réti, Symmetrical" },
  { moves: ["Nf3","Nf6","c4"], name: "Réti Opening" },
  { moves: ["Nf3","d5","c4"], name: "Réti Opening" },
  { moves: ["Nf3","c5","c4","Nf6","Nc3","d5","cxd5","Nxd5","d4"], name: "Symmetrical English / Réti" },
  { moves: ["Nf3","c5","c4","Nc6","Nc3","Nf6","g3","g6","Bg2","Bg7","O-O","O-O","d4"], name: "English/Réti" },
  { moves: ["Nf3","Nf6","g3","d5","Bg2","c6","O-O","Bg4","d3","Nbd7","Nbd2"], name: "King's Indian Attack vs Caro-Kann" },
  { moves: ["Nf3","e6","c4","Nf6","g3","d5","Bg2","Be7","O-O","O-O","d4","Nbd7"], name: "Réti → QGD" },
  { moves: ["Nf3","e6","g3","d5","Bg2","Nf6","O-O","c5","d3","Nc6"], name: "King's Indian Attack" },
  { moves: ["Nf3","e6","g3","d5","Bg2","Nf6","O-O","Be7","d3"], name: "King's Indian Attack" },
  { moves: ["Nf3","e6","g3"], name: "King's Indian Attack" },
  { moves: ["Nf3","Nc6","d4","d5","c4","e6","Nc3","Nf6"], name: "Réti → QGD" },
  { moves: ["Nf3","Nc6","c4","e5","Nc3","Nf6","g3","Bb4","Bg2","O-O","O-O","Re8"], name: "Réti, Four Knights" },
  { moves: ["Nf3","f5","d3","Nf6","g3","g6","Bg2","Bg7","O-O","O-O","c4"], name: "Réti → Dutch" },
  { moves: ["Nf3","g6","g3","Bg7","Bg2","Nf6","O-O","O-O","d3","d6","c4"], name: "King's Indian Attack" },
  { moves: ["Nf3","d5"], name: "Réti Opening" },
  { moves: ["Nf3","Nf6"], name: "Réti Opening" },
  { moves: ["Nf3","c5"], name: "Réti Opening" },
  { moves: ["Nf3"], name: "Réti Opening" },

  // ── Rare first moves ────────────────────────────────────────────────────────
  { moves: ["b3","e5","Bb2","Nc6","e3","d5","Bb5","Bd6","Nf3","Nge7","d4","exd4","exd4","O-O","O-O"], name: "Nimzowitsch-Larsen, Classical" },
  { moves: ["b3","e5","Bb2","Nc6","c4","Nf6","Nf3","Nd4","Nxd4","exd4"], name: "Nimzowitsch-Larsen Attack" },
  { moves: ["b3","d5","Bb2","Nf6","Nf3","g6","g3","Bg7","Bg2","O-O","O-O","c5","c4"], name: "Nimzowitsch-Larsen Attack" },
  { moves: ["b3","e5","Bb2","Nc6","e3"], name: "Nimzowitsch-Larsen Attack" },
  { moves: ["b3","d5","Bb2"], name: "Nimzowitsch-Larsen Attack" },
  { moves: ["b3"], name: "Nimzowitsch-Larsen Attack" },
  { moves: ["b4","e5","Bb2","Bxb4","Bxe5","Nf6","Nf3","O-O","e3","d5","c4","Bb6"], name: "Polish Opening, Outflank" },
  { moves: ["b4","e5","Bb2","Bxb4","Bxe5"], name: "Polish, Tartakower Gambit" },
  { moves: ["b4","e5","Bb2","f6","e4","Bxb4","Bc4","Nc6","Ne2","d6","O-O","Be6"], name: "Polish Opening" },
  { moves: ["b4","d5","Bb2","Nf6","e3","e6","b5","c5","bxc6","Nxc6","Nf3","Bd6"], name: "Polish, Queen's Indian" },
  { moves: ["b4","e5","Bb2"], name: "Polish Opening" },
  { moves: ["b4","d5","Bb2"], name: "Polish Opening" },
  { moves: ["b4"], name: "Polish Opening" },
  { moves: ["f4","d5","Nf3","Nf6","e3","g6","b3","Bg7","Bb2","O-O","Be2","c5"], name: "Bird's Opening, Classical" },
  { moves: ["f4","d5","Nf3","Nf6","e3","e6","b3","Be7","Bb2","O-O","Be2","c5"], name: "Bird's, Lasker Variation" },
  { moves: ["f4","d5","Nf3","Nf6","e3","Bg4","Be2","e6"], name: "Bird's Opening" },
  { moves: ["f4","e5","fxe5","d6","exd6","Bxd6","Nf3","g5","d4","g4","Ne5","Nf6","Ng4","Nxg4","Qxg4"], name: "From's Gambit" },
  { moves: ["f4","e5","fxe5","d6","exd6","Bxd6"], name: "From's Gambit" },
  { moves: ["f4","e5"], name: "From's Gambit" },
  { moves: ["f4","d5","Nf3"], name: "Bird's Opening" },
  { moves: ["f4","Nf6","Nf3","d5","b3","e6","Bb2","Be7","e3","O-O","Be2","c5"], name: "Bird's Opening" },
  { moves: ["f4","d5","e3","Nf6","Nf3","g6","b3","Bg7","Bb2","O-O","Be2","c5"], name: "Bird's Opening" },
  { moves: ["f4","d5","e3"], name: "Bird's Opening" },
  { moves: ["f4","d5"], name: "Bird's Opening" },
  { moves: ["f4"], name: "Bird's Opening" },
  { moves: ["g3","d5","Bg2","e5","d3","Nf6","Nd2","Bc5","e4","dxe4","dxe4","O-O","Ngf3","Nc6"], name: "King's Indian Attack" },
  { moves: ["g3","d5","Bg2","c6","Nf3","Bg4","O-O","Nd7","d3","e5","Nbd2"], name: "King's Indian Attack" },
  { moves: ["g3","d5","Bg2","e5","d3","Nf6","Nf3","Nc6","O-O","Be7","Nbd2"], name: "King's Indian Attack" },
  { moves: ["g3","d5","Bg2","Nf6","Nf3","c6","O-O","Bf5","d3","Nbd7","Nbd2"], name: "King's Indian Attack" },
  { moves: ["g3","Nf6","Bg2","d5","Nf3","c5","O-O","Nc6","d3","e6","Nbd2"], name: "King's Indian Attack" },
  { moves: ["g3","e5","Bg2","d5","Nf3","Nc6","O-O","Be7","d3","O-O","Nbd2","a5"], name: "King's Indian Attack" },
  { moves: ["g3","d5","Bg2"], name: "Hungarian Opening" },
  { moves: ["g3","Nf6","Bg2","d5"], name: "Hungarian Opening" },
  { moves: ["g3","e5","Bg2"], name: "Hungarian Opening" },
  { moves: ["g3"], name: "Hungarian Opening" },
  { moves: ["d3","d5","Nd2","e5","Ngf3","Nc6","g3","Nf6","Bg2","Be7","O-O","O-O","e4","dxe4","dxe4"], name: "King's Indian Attack" },
  { moves: ["d3","e5","Nd2","Nf6","Ngf3","Bc5","g3","d5","Bg2","O-O","O-O","Re8","Re1","Nc6"], name: "King's Indian Attack" },
  { moves: ["d3","d5","Nd2","e5","e4","Nf6","Ngf3","Nc6","g3","Be7","Bg2","O-O","O-O"], name: "King's Indian Attack" },
  { moves: ["d3","e5","g3","Nf6","Bg2","d5","Nd2","Nc6","e4","dxe4","dxe4","Bc5","Ngf3"], name: "King's Indian Attack" },
  { moves: ["d3","d5","Nd2","Nf6","Ngf3","e6","g3","Be7","Bg2","O-O","O-O","c5"], name: "King's Indian Attack" },
  { moves: ["d3","d5","e4","Nf6","Nd2","e5","Ngf3","Nc6","g3","Bc5","Bg2","O-O","O-O"], name: "King's Indian Attack" },
  { moves: ["d3","e5","Nd2","Nc6","Ngf3","d5","g3","Be6","Bg2","Qd7","O-O","O-O-O"], name: "King's Indian Attack" },
  { moves: ["d3","Nf6","g3","d5","Bg2","c6","Nf3","Bg4","O-O","Nbd7","Nbd2"], name: "King's Indian Attack" },
  { moves: ["d3","e5","g3","d5","Bg2","c6","Nd2","Nf6","Ngf3","Bd6","O-O","O-O"], name: "King's Indian Attack" },
  { moves: ["d3","d5","g3","Nf6","Bg2","e5","Nf3","Nc6","O-O","Be7","Nbd2"], name: "King's Indian Attack" },
  { moves: ["d3","Nf6","Nd2","e5","e4","d5","Ngf3","Bc5","g3","O-O","Bg2","c6","O-O"], name: "King's Indian Attack" },
  { moves: ["d3","c5","e4","Nc6","Nd2","g6","Ngf3","Bg7","g3","d6","Bg2","e5","O-O","Nge7"], name: "King's Indian Attack" },
  { moves: ["d3","e5","Nd2","d5","e4","Nf6","Ngf3","Nc6","g3","Bc5","Bg2","O-O","O-O"], name: "King's Indian Attack" },
  { moves: ["d3","d5","Nd2","e5","Ngf3"], name: "King's Indian Attack" },
  { moves: ["d3","e5","Nd2","Nf6","Ngf3"], name: "King's Indian Attack" },
  { moves: ["d3","Nf6","Nd2","d5","Ngf3","e6","g3","c5","Bg2","Be7","O-O","Nc6","Re1"], name: "King's Indian Attack" },
  { moves: ["d3","d5","Nd2"], name: "King's Indian Attack" },
  { moves: ["d3","e5","e4","Nf6","g3","d5","exd5","Nxd5","Bg2","Nc6","Ne2","Be7","O-O","O-O","Nbc3"], name: "King's Indian Attack" },
  { moves: ["d3","e5","e4","Nc6","Be2","Nf6","Nf3","d5","exd5","Nxd5","O-O","Be7","Nbd2"], name: "King's Indian Attack" },
  { moves: ["d3","e5","Nd2"], name: "King's Indian Attack" },
  { moves: ["d3","d5"], name: "King's Indian Attack" },
  { moves: ["d3","e5"], name: "King's Indian Attack" },
  { moves: ["d3"], name: "King's Indian Attack" },
  { moves: ["Nc3","d5","d4","Nf6","Bg5","e6","e4","Bb4","e5","h6","Bh4","g5","Bg3","Ne4","Nxe4","dxe4"], name: "Dunst, Reversed Nimzowitsch" },
  { moves: ["Nc3","Nf6","e4","d5","e5","Ne4","Nxe4","dxe4","d3","exd3","Bxd3","Nc6","Nf3"], name: "Dunst Opening" },
  { moves: ["Nc3","d5","e4","d4","Nce2","c5","Ng3","Nc6","Bc4","Nf6","N1e2"], name: "Van Geet / Dunst" },
  { moves: ["Nc3","d5","d4","c5","Nf3","Nc6","e4","d4","Ne2","e5","Ng3","Nf6","Bc4","Bg4"], name: "Dunst / Sicilian blend" },
  { moves: ["Nc3","d5","d4","e6","Nf3","Nf6","Bg5","Be7","e3","O-O","Bd3"], name: "Dunst → QGD" },
  { moves: ["Nc3","Nf6","d4","d5","Nf3","e6","Bg5","Be7","e3","O-O","Bd3","c5"], name: "Dunst → QGD" },
  { moves: ["Nc3","c5","Nf3","Nc6","d4","cxd4","Nxd4","e6","e4","a6","Be2","Qc7","O-O","Nf6","Be3","Be7"], name: "Dunst → Sicilian Taimanov" },
  { moves: ["Nc3","e5","Nf3","Nc6","d4","exd4","Nxd4","Nf6","g3","Bc5","Bg2","O-O","O-O","Re8"], name: "Dunst → Scotch" },
  { moves: ["Nc3","Nf6","e4","d5","exd5","Nxd5","d4","g6","Nf3","Bg7","Be2","O-O","O-O","c6","Re1","Nxc3","bxc3","b6"], name: "Dunst → Scandinavian" },
  { moves: ["Nc3","d5","e4","d4","Nce2"], name: "Dunst Opening" },
  { moves: ["Nc3","d5","d4"], name: "Dunst / Van Geet" },
  { moves: ["Nc3","Nf6","e4"], name: "Dunst Opening" },
  { moves: ["Nc3","e5","e4","Nf6","Nf3","Nc6","d4","exd4","Nxd4","Bb4","Nxc6","bxc6","Bd3"], name: "Dunst → Scotch" },
  { moves: ["Nc3","c5","e4","Nc6","f4","g6","Nf3","Bg7","Bc4","e6","f5","gxf5","exf5","d5","fxe6","dxc4"], name: "Dunst → Grand Prix" },
  { moves: ["Nc3","d5","e4","e6","d4","Bb4","exd5","Nf6","dxe6","fxe6","Bd3","Bxc3+","bxc3","O-O"], name: "Dunst → French" },
  { moves: ["Nc3","d5","Nf3","c6","d4","Nf6","Bg5","Bf5","e3","e6","Bd3","Bxd3","Qxd3","Nbd7","O-O"], name: "Dunst → Caro-Kann" },
  { moves: ["Nc3","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","e4","a6","Be2","e5","Nb3","Be7","O-O","O-O","Be3"], name: "Dunst → Sicilian Najdorf" },
  { moves: ["Nc3","e5","d4","exd4","Qxd4","Nc6","Qe3","Nf6","Nf3","Be7","Bd2","O-O","O-O-O"], name: "Dunst / Center-Counter" },
  { moves: ["Nc3","Nf6","d4","d5","Nf3","e6","Bg5","Be7","e3","O-O","Bd3","Nbd7","O-O","c5","cxd5","Nxd5","Bxe7","Qxe7","Nxd5","exd5","dxc5","Nxc5","Bc2"], name: "Dunst → QGD Exchange" },
  { moves: ["Nc3","Nf6","Nf3","d5","d4","e6","Bg5","Be7","e3","O-O","Bd3","Nbd7","O-O","c5","cxd5","Nxd5","Bxe7","Qxe7","Nxd5","exd5","Re1","Rac8","Qd2"], name: "Dunst → QGD Orthodox" },
  { moves: ["Nc3","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","e4","e5","Ndb5","a6","Nd6+","Bxd6","exd6","Qxd6","Bg5","Qxd1+","Rxd1","b5","Nd5","Nxd5","Bxd5","Ra7"], name: "Dunst → Pelikan/Sveshnikov" },
  { moves: ["Nc3","e5","e4","Nc6","Bc4","Bc5","Nf3","d6","d3","Nf6","O-O","O-O","Na4","Bb6","Nxb6","axb6","c3"], name: "Dunst → Giuoco Piano-ish" },
  { moves: ["Nc3","Nf6","d4","g6","e4","d6","Nf3","Bg7","Be2","O-O","O-O","Nc6","d5","Ne5","Nxe5","dxe5","f4","exf4","Bxf4","c5","dxc6","bxc6"], name: "Dunst → Pirc/KID blend" },
  { moves: ["Nc3","d5","d4","Nf6","Nf3","e6","Bg5","c5","e3","Nc6","Bd3","cxd4","exd4","Be7","O-O","O-O","Re1","a6","a3","b5","Bb1","Bb7","Qd3","Nb4","Qh3","g6"], name: "Dunst → QGD blend" },
  { moves: ["Nc3","d5","d4","Nf6","Bg5","e6","e3","Be7","Nf3","O-O","Bd3","Nbd7","O-O","c5","Re1","b6","e4","dxe4","Nxe4","Bb7","Nxf6+","Nxf6","Ne5","Qc7","Bxe7","Qxe7","Nd7","Rfe8","Nxf6+","Qxf6","Bc4","cxd4","Qxd4"], name: "Dunst → Exchange QGD" },
  { moves: ["Nc3","d5","d4","c6","Nf3","Nf6","Bg5","h6","Bh4","g5","Bg3","Ne4","Nxe4","dxe4","Ne5","Nd7","Nxd7","Qxd7","e3","h5","Bc4","h4","Bh2","Bg7","c3"], name: "Dunst → Caro-Kann w/g5" },
  { moves: ["Nc3","g6","e4","Bg7","d4","d6","Nf3","Nf6","Be2","O-O","O-O","Nc6","d5","Ne5","Nxe5","dxe5","Be3","c6","dxc6","bxc6","Qd3","Nd7","Rad1","Nc5","Qd6","Qxd6","Rxd6","Ne6","Rfd1","Rd8","R6d2","Rxd2","Rxd2","Rb8","b3","Nf4","Bf1","Bh6","Bd4","exd4","Rxd4"], name: "Dunst → Modern/Pirc" },
  { moves: ["Nc3","d5","e4","e6","d4","Nf6","e5","Nfd7","f4","c5","Nf3","cxd4","Nxd4","Nc6","Be3","Bc5","Bb5","O-O","Bxc6","bxc6","Nxc6","Qb6","Nd4","Bb7","Qg4","f6","exf6","Nxf6","Qg3","Ne4","Nxe4","dxe4","O-O","Qxd4+","Qxd4","Bxd4+","Rxd4","Rad8","Rxd8","Rxd8","f5","exf5","Kf2"], name: "Dunst → French Advance" },
  { moves: ["Nc3","Nf6","e4","d5","e5","d4","exf6","dxc3","fxg7","cxd2+","Qxd2","Bxg7","Qxd7+","Kf8","Qxc7","Qxd1+","Kxd1","Nc6","Bb5","e5","Bxc6","bxc6","Bc1","Rb8","b3","Rxb3","axb3","Bg4+","Ke1","e4","h3","Bh5","Ne2","Ke7","Ng3","Bg6","Kf1","f5","Nxf5+","Bxf5","Ra8","Bb1","Kg1","Rd8","Rxa7","Bc2","Ra2","Rd1#"], name: "Dunst → Alekhine blend" },
  { moves: ["Nc3","e5","Nf3","Nc6","Bb5","a6","Bxc6","dxc6","Nxe5","Qd4","Nd3","Qxe4+","Qe2","Qxe2+","Kxe2"], name: "Dunst → Ruy Lopez Exchange" },
  { moves: ["Nc3","c5","e4","Nc6","Bb5","Nd4","Bc4","Nf6","Nf3","Nxf3+","Qxf3","d6","d3","g6","O-O","Bg7","Be3","O-O","Rae1","a6","a4","b5","axb5","axb5","Bb3","Qb6","Bg5","Nd7","Nd5","Qa7","Bxe7","Nxe7","Nxe7+","Rxe7","Rxe7","Bxb2","Rxf7","Rxf7","d4","cxd4","e5","Rf8","e6","Qxe7","dxe7","Rf2","e8=Q+","Rxe8","Qxf2+","Kh1","Bxc2","Bxc2","Rxe2","Qxe2","d3","Qd2","Bc3","Qf4","Bg7","h4","c4","Bc1","c3","Kh2","c2","Qf3","c1=Q","Bxd3","Bxd3#"], name: "Dunst → Sicilian/Ruy blend" },
  { moves: ["Nc3","d5","d4","c5","Nf3","cxd4","Nxd4","Nf6","e3","e6","Be2","Nc6","O-O","Bd6","Re1","O-O","Nxc6","bxc6","e4","dxe4","Nxe4","Nxe4","Rxe4","Bc7","Bf3","c5","Bg5","Qd7","Rxc4","Bb7","Bxb7","Qxb7","b3","Rac8","Rxc8","Rxc8","Qg4","Qd5","Be3","Rd8","Rd1","Qc6","Rxd8+","Qxd8","Qe4","Qb6","Bxc5","Qxb3","Qxb7","a5","Qa6"], name: "Dunst → QGD blend" },
  { moves: ["Nc3","Nf6","Nf3","d5","e3","c5","d4","Nc6","Bb5","cxd4","exd4","Bg4","h3","Bh5","O-O","e6","Re1","Bd6","Bg5","O-O","Bxc6","bxc6","Bxf6","Qxf6","Ne5","Bxd1","Rexd1","Rfe8","Nxc6","Qg6","Ne7+","Rxe7","Rd3","Re8","Rf3","Qg5","Ne2","h5","Nf4","g6","Re1","Rxe1+","Rxe1","Kf8","g3","Rh8","Kg2","Rh6","Re3","Rd6","Re2","Ke7","Ng2","Kf6","Nf4","h4","gxh4","Rxh4","Nxg6","fxg6","Re6+","Kf7","Rxd6","Qxh3+","Kf2","Qxd3","c3","Qd2+","Kg3","Qe1+","Kh3"], name: "Dunst → QGD Three Knights" },
  { moves: ["Nc3","e5","e4","Nc6","Nf3","Nf6","Bc4","Bc5","d3","d6","O-O","O-O","Bg5","h6","Bh4","g5","Bg3","Nh5","Nd5","Nxg3","fxg3","Bb6","Nxb6","axb6","c3","g4","Ne1","f5","exf5","Bxf5","d4","exd4","cxd4","d5","Bb5","Ne7","Nc2","Ng6","Ne3","Bg7","Bc6","Rb8","d5","Nh4","gxh4","gxh4","Qf3","Qf6","Qf5","Qxf5","Nxf5","Bxb2","Rab1","Bxa3","Nxh4","Bg7","Nf5","Bh8","Rxb6","Rxb6","Bxb6","Rxf5","Rxf5","Bg7","Rf7","Kg8","Bc7","h5","Bd6","Kh7","Be8+","Kg8","Bd7"], name: "Dunst → Italian" },
  { moves: ["Nc3","Nf6","e4","d5","e5","Ne4","d4","Nxc3","bxc3","e6","Nf3","c5","c4","cxd4","cxd4","Nc6","Be2","dxc4","Bxc4","Nb4","Bb5+","Bd7","Bxd7+","Qxd7","a3","Nd5","O-O","Be7","Re1","O-O","Bd2","Rac8","Rc1","Rxc1","Qxc1","Rc8","Qb2","b6","Ne1","Qc6","Nd3","Qa4","Bc3","Nxc3","Qxc3","Qxa3","Nb4","Rc4","Nc6","a5","Qa7","Bg5","h3","Be7","Nd8","Rxf2","Kxf2","Qa7+","Kf1","Qxb4","Nxe6","fxe6","Qxe6+","Kh7","Qe7","Rc1+","Ke2","Rc2+","Kd3","Rxg2","Kc4","Rh2","Qxe7","b5+","Kc5","b4","Qd7","Rxh3","Qe8","Rh2","d5","b3","d6","h5","d7","h4","d8=Q","Rxd8","Qxd8+","Kxd8"], name: "Dunst → Scandinavian/e5 blend" },
  { moves: ["Nc3","d5","d4","Nf6","Bg5","Nbd7","e3","e6","Nf3","Be7","Bd3","O-O","O-O","c5","Ne5","cxd4","exd4","Nxe5","dxe5","Ne4","Bh4","Nxd3","cxd3","Qb6","b3","Qxb2","Rb1","Qxa3","Rxb7","Bg5","f4","Bxf4","Rxf4","Qa5","Qd2","Rfc8","Rcb4","a6","R4b6","Rc2","Qd3","Rxh2","Kxh2","Qxb6","Rxb6","Rd8","Bf6","gxf6","exf6","d4","f7+","Kg7","Rxe6","dxc3","Re7+","Kf6","Rxh7","c2","Rh1","Kxf7","Rc1","Ke6","Kh3","d3","Kg4","c1=Q","Rxc1","d2","Re1","Ke5","Rxd2","Kf4"], name: "Dunst → QGD" },
  { moves: ["Nc3","Nf6","Nf3","c5","d4","cxd4","Nxd4","d5","Bg5","e6","e3","Be7","Bb5+","Bd7","Bxd7+","Nbxd7","O-O","a6","Re1","Rc8","e4","dxe4","Nxe4","O-O","Nxf6+","Nxf6","Bxf6","Bxf6","Nb3","b5","Nd2","Qe7","Nf3","Rfd8","Qe2","Qd7","Rd1","Qc6","a3","Rd7","Rxd7","Qxd7","Qe3","Be7","Nd4","Rc4","Nb3","Rc6","Na5","Rc7","Rd1","Qc6","g3","Rc8","Rd7","Kf8","c4","b4","axb4","Bxb4","Rd2","Be7","Kg2","Bc5","Qf3","Qxf3+","Kxf3","e5","Ke4","Ke7","Ke3","Kd6","Kd3","f5","b4","Bd4","Nb3","f4","gxf4","exf4","c5+","Ke5","Nd2","Bxf2","Nc4+","Kf5","Nd6+","Kg6","Nxc8","Rxc8","Rxd4","Rxc5","Rd6+","Kh5","Rxg6","hxg6","Kd4","f3","h3","g5","Ke4","Kh4","Kf5","g4","hxg4+","Kxg4","Kg6","f2","Kh6"], name: "Dunst → Sicilian blend" },
  { moves: ["Nc3"], name: "Van't Kruijs / Dunst Opening" },
  { moves: ["a3"], name: "Anderssen's Opening" },
  { moves: ["a4"], name: "Ware Opening" },
  { moves: ["e3"], name: "Van't Kruijs Opening" },
  { moves: ["h3"], name: "Clemenz Opening" },
  { moves: ["h4"], name: "Kadas Opening" },
];

export function getOpeningName(sans: string[]): string | null {
  let best: Opening | null = null;
  for (const opening of OPENINGS) {
    if (opening.moves.length > sans.length) continue;
    const matches = opening.moves.every((san, i) => san === sans[i]);
    if (matches && (!best || opening.moves.length > best.moves.length)) {
      best = opening;
    }
  }
  return best?.name ?? null;
}
